### ISSUE TITLE
Support fetchSubmodules for git/github

### ISSUE THREAD

**Issue by LunNova** [andir/npins#45]
Some projects need submodules to build, npins doesn't seem to support this.

Example where this came up: https://github.com/fufexan/nix-gaming/pull/86

**Comment by piegamesde** [comment]
The git source type tries to use tarballs when pulling from GitHub or GitLab, and those don't provide submodules. So the option would probably only be there for generic git repository URLs. But I'll try to give it a look.

Alternatively, since `builtins.fetchGit` does not seem to take a hash, maybe adding an `override` method to inject custom parameters would be an idea?

**Comment by adamcstephens** [comment]
I just ran into this trying to pin river master which needs submodule support.

**Comment by bwkam** [comment]
Any updates on this?
